### ISSUE TITLE
Write validation scripts for data before pushing to s3

### ISSUE THREAD

**Issue by lxu213** [HopkinsIDD/covid-dashboard-app#107]
## Geoid files
- [x] Validate total number of geoid files is expected: county number + state number

- [x] Validate first key in geoid file (06085.json) is run_date. No period, semicolon, colon, etc in key.

- [x] Validate next key can only be low, med or high

- [x] Validate object includes name, max, over, r0, and vals

- [x] Validate length of vals is same as overall length of dates

- [x] Validate indicators only includes expected incidI, incidH, etc from outcomes.json

## statsForMap 

- [x] Validate state key is first, and then county key

- [x] Validate scenario_name matches geoid scenario_name

- [x] Keys are exactly as expected - from outcomes.json

# countyBoundaries

- [x] Check stats exists in statsForMap and countyBoundaries

## Actuals files

- [x] Validate number of expected actuals files

- [x] Contains expected reported data 

## Requested Feature

- [x] Run and test validator on just one geoid

**Comment by veev** [comment]
Include validation for dateThreshold in scenario name key

**Comment by lxu213** [comment]
@veev Where in the code does dateThreshold use scenario name key?

**Comment by lxu213** [comment]
@veev Nevermind, I covered all the cases.
