### ISSUE TITLE
Scenario simulation file availability

### ISSUE THREAD

**Issue by ajhool** [HopkinsIDD/covid-dashboard-app#21]
@veev @lxu213 Hi, jhu alum and would love to contribute to this project. Is there a scenario simulation file available for dev server to spin up with?

**Comment by lxu213** [comment]
@ajhool thanks for your interest - all the files required to start development are located in store. We don't have a roadmap yet unfortunately but hope to have one in the coming weeks.

**Comment by ajhool** [comment]
@lxu213 thank you!
