### ISSUE TITLE
Add more narration text

### ISSUE THREAD

**Issue by lxu213** [HopkinsIDD/covid-dashboard-app#24]
- Add landing text that explains there are 3 types of views and what to expect in each, "scroll for more"
- Add more description on each view, including guidance on how to interact with the menus

**Comment by lxu213** [comment]
I added some narration text to the "landing spot" and also to the views. Graph is complicated so of course it's busiest. Right now, it's mostly a vomit of words - do you have any ideas on how this could be more intuitive/story-like/easier to follow? I thought maybe we can add the view icons to where its listed out, but then it's redundant to the menu, but maybe that's okay? Or have user be able to click it and then go down to that view?

I'm also thinking of adding a [? icon](https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Icon-round-Question_mark.svg/1024px-Icon-round-Question_mark.svg.png) next to the individual parameters in menu that they can click on for more scientific information (like severity, and R0).

For Graph, we also have the problem now that the whole container takes up more than the screen height, but alas.

![Screen Shot 2020-06-04 at 11 11 04 AM](https://user-images.githubusercontent.com/16282020/83795678-aa216380-a654-11ea-98f1-93c80140a630.png)
![Screen Shot 2020-06-04 at 11 11 39 AM](https://user-images.githubusercontent.com/16282020/83795681-ab529080-a654-11ea-9746-3a38c9d046cb.png)
![Screen Shot 2020-06-04 at 11 11 47 AM](https://user-images.githubusercontent.com/16282020/83795683-ab529080-a654-11ea-9b86-30ad16dcbe4d.png)
![Screen Shot 2020-06-04 at 11 13 26 AM](https://user-images.githubusercontent.com/16282020/83795685-abeb2700-a654-11ea-8e7a-9c1571e8a762.png)

It's also up on https://github.com/HopkinsIDD/covid-dashboard-app/tree/narration

**Comment by lxu213** [comment]
FYI, I added our info tooltip back since our side menu is starting to get crowded. I'm thinking scientific/additional information can live in those tooltips while information on how to use/interact with the menu can go in the landing text. Open to feedback/tweaking it.

**Comment by veev** [comment]
I like the look of this, and think it's smart to put the description in the info icon again. I wonder if we want to try matching the style of the Tooltips

**Comment by lxu213** [comment]
Yeah that's a good idea. Which style do you prefer?
