### ISSUE TITLE
Add actuals data as an overlay to Graph

### ISSUE THREAD

**Issue by lxu213** [HopkinsIDD/covid-dashboard-app#31]
- the team is pulling USA Facts into their code and it includes some cleaning functions: https://github.com/HopkinsIDD/COVIDScenarioPipeline/blob/inference/R/pkgs/covidcommon/R/USAFacts.R (edited) 
- figure out if we need to make some kind of CRON/Lambda job that pulls this data in every day

**Comment by lxu213** [comment]
@veev Actuals data is hooked up on `actuals` branch and is now being sent to `Graph Container`. When you get the chance, can you add the d3 visualizations?

**Comment by veev** [comment]
I added this on the `actuals` branch with commit `ffe6137270b016610ab6f85d8c91deb74fa202c6`
