### ISSUE TITLE
Ensure users know which county or state is selected

### ISSUE THREAD

**Issue by lxu213** [HopkinsIDD/covid-dashboard-app#36]
- Hook up search bar so it is in sync with main search bar
- Decide on design and location - if ant design search bar should be used

**Comment by lxu213** [comment]
This commit contains the work already done (but has since been removed) for implementing a search bar in the menu --> 

https://github.com/HopkinsIDD/covid-dashboard-app/commit/f8c9806d7bcf05ff9e2e1d6a3a1e60b075c2c45f

**Comment by lxu213** [comment]
@veev Here's a brainstorm for some ideas besides adding a search bar to the menu, given the issues we had with that strategy (styling, design, complex functionality, etc):

1. Make the CountyName the title of the Graph/Chart/Map Containers - this is similar to your initial approach. It's easy for Chart, but might be busy for Graph/Map
![Screen Shot 2020-06-03 at 8 48 04 AM](https://user-images.githubusercontent.com/16282020/83658620-4d03b000-a577-11ea-9c5f-3e8f2dd82e56.png)
![Screen Shot 2020-06-03 at 8 48 35 AM](https://user-images.githubusercontent.com/16282020/83658624-4d9c4680-a577-11ea-8086-002271844a6f.png)
![Screen Shot 2020-06-03 at 8 50 19 AM](https://user-images.githubusercontent.com/16282020/83658625-4e34dd00-a577-11ea-9e41-3a04f629016e.png)

Then we would just add a magnifying glass / search breadcrumb so users can easily research for a county if they wanted to.

2. Add the countyName to the middle of the menu and if the user click on it, it brings them to the Search component. This is low effort, easy implementation solution but might look weird.

3. Add to the sidebar a disabled box for REGION and display countyName.

**Comment by veev** [comment]
I agree that option 1 looks best for Chart. I can look into styling the Geoid and Scenario slightly differently, for instance, with bolding, uppercasing or color.

Option 2 could potentially work, but may not be intuitive from a UI perspective. Also may look strange as you mention. This may be worth trying just to see though.

Not sure we have room in Graph for Option 3, and would want to choose something that can work well for all three views. Will attempt Options 1 and 2 and post screenshots.

**Comment by veev** [comment]
Option 2 Screenshot. One thing I hadn't considered about this option is that the way we have structured NavBar requires lifting the geoid logic into App from MainContainer. Alternatively, we could make NavBar have absolute positioning and load it in MainContainer

![image](https://user-images.githubusercontent.com/626371/83717220-28074f80-a600-11ea-8f6a-536dd5f33c38.png)

**Comment by veev** [comment]
Option 1 Screenshots. I gave the geoid its own line and typography. I'm inclined to go with this but let me know what you prefer.

![image](https://user-images.githubusercontent.com/626371/83718688-9568af80-a603-11ea-8771-2c3040ed878d.png)

![image](https://user-images.githubusercontent.com/626371/83718729-a5808f00-a603-11ea-9121-05d38d8b8d65.png)

**Comment by lxu213** [comment]
@veev I also prefer Option 1 - it's easy to implement plus the typography and separate line keeps it from being cluttered!

**Comment by lxu213** [comment]
Resolved by https://github.com/HopkinsIDD/covid-dashboard-app/commit/6a86f65513ae2c76344d8ea37d6b34b36fcc6e13
