### ISSUE TITLE
Too many tooltips bug on Map

### ISSUE THREAD

**Issue by veev** [HopkinsIDD/covid-dashboard-app#38]
This happens on hover when you hover over a tooltip that is already open, as well as on click and drag events.

![image](https://user-images.githubusercontent.com/626371/83588849-4269fc00-a520-11ea-9c2b-30231299de32.png)

**Comment by veev** [comment]
I believe this has been addressed in the latest `[commits](https://github.com/HopkinsIDD/covid-dashboard-app/commit/655c858909038926d5829c34561e08bbb7335f8b)` to master. Let me know if you're still encountering this behavior.

**Comment by lxu213** [comment]
Just checked it out and it looks good! Also no more tooltips following me around on the page which is great.
