### ISSUE TITLE
Date axis in Graph is crowded on load

### ISSUE THREAD

**Issue by lxu213** [HopkinsIDD/covid-dashboard-app#52]
@veev 

![Screen Shot 2020-06-09 at 5 44 41 PM](https://user-images.githubusercontent.com/16282020/84215031-f700a200-aa79-11ea-8125-5ecc1db4ae6e.png)

**Comment by veev** [comment]
I think this has been addressed with this commit to main branch: [37abc1525978aa328a1d72083ae8484e02f43da5](https://github.com/HopkinsIDD/covid-dashboard-app/commit/37abc1525978aa328a1d72083ae8484e02f43da5)

**Comment by lxu213** [comment]
Looks good!
