### ISSUE TITLE
Adding types (flow/TypeScript)

### ISSUE THREAD

**Issue by BenjiLee** [HopkinsIDD/covid-dashboard-app#54]
@veev @lxu213 

Looks like Typescript is already installed in this project, just not in use. 

Are there any plans to start using typescript? I can start converting files slowly and frequently to avoid major changes to code during development.

**Comment by lxu213** [comment]
@BenjiLee of course this would be awesome to have, however, I have some concerns around this migration:
- how can we prevent introducing bugs and regressions in the code? the components and functions on the frontend are basically untested so we would need to thoroughly manually test the app each push or spend some time to add tests
- I'm not that familiar with it so I'm concerned about what unknown unknowns there are
- there are a lot of files that would need to be converted. I'm reading online that TS migrations can take a year, depending on how large your code base is, which is a tall order for a project I envision is largely wrapping up.

**Comment by BenjiLee** [comment]
> how can we prevent introducing bugs and regressions in the code? the components and functions on the frontend are basically untested so we would need to thoroughly manually test the app each push or spend some time to add tests
> I'm not that familiar with it so I'm concerned about what unknown unknowns there are

It adds type validation to your code but would only complain about it. Only thing to watch out for is making sure the that imports are pointing to the right file since using Typescript is just making a Javascript file end in `.ts` instead of `.js`. Otherwise the code behaves the same exact way.

> there are a lot of files that would need to be converted. I'm reading online that TS migrations can take a year, depending on how large your code base is, which is a tall order for a project I envision is largely wrapping up.

This project isn't that big so it shouldn't take a year :D Files can be migrated piece by piece so you can still get the benefits gradually.

**Comment by lxu213** [comment]
Sounds good - definitely open to seeing an example and exploring this.

**Comment by lxu213** [comment]
Closing this issue for now but willing to re-open when there's more time/developer enthusiasm!

**Comment by BenjiLee** [comment]
Added Flow  (https://github.com/HopkinsIDD/covid-dashboard-app/pull/86) vs TS (https://github.com/HopkinsIDD/covid-dashboard-app/pull/89) examples

**Comment by lxu213** [comment]
We both use vscode, which I know definitely supports TS, not sure about Flow.

When you say TS forces type checking, this means Flow wouldn't be able to do that unless we added CI or always ran flow checks? Type checking is one of the main reasons for this migration to prevent bug introduction, so that sounds like a pretty big con against Flow.

**Comment by lxu213** [comment]
Gotcha... let's stick with TypeScript!
