### ISSUE TITLE
Make r0 filtering more intuitive

### ISSUE THREAD

**Issue by lxu213** [HopkinsIDD/covid-dashboard-app#63]
- [x] Add a resample button
- [x] Decide on transition animation that is not confusing, might be simply turning it off
- [x] Add some kind of viz in slider, histogram or bar, that indicates the "percentage" of simulations shown

**Comment by veev** [comment]
@lxu213 Let me know your thoughts on the transition changes. If you like them, thinking we can close this one out soon.
