### ISSUE TITLE
Add severity labels to Chart x-axis

### ISSUE THREAD

**Issue by lxu213** [HopkinsIDD/covid-dashboard-app#67]

**Comment by lxu213** [comment]
@veev you mentioned that these axis were in the code base at some point right? Do you have any recollection which branch/commits it might exist in so we can repopulate?

**Comment by veev** [comment]
I think I was mistaken. The issue is that with six scenarios, it looks
quite busy. My suggestion would be to only reveal severity labels if there
are 3 scenarios or less. Not sure how the scientists will feel. The info is
revealed in the tooltip. Thoughts?

**Comment by lxu213** [comment]
Gotcha, yeah that solution makes sense to me. Only other idea I had is maybe if there are more than 3 scenarios, instead of xaxis labels, it could be distinguished based on colors or border thickness or some other differentiating style?
