### ISSUE TITLE
Tooltip not appearing on all Chart bars

### ISSUE THREAD

**Issue by lxu213** [HopkinsIDD/covid-dashboard-app#68]

**Comment by veev** [comment]
@jkamins7 I haven't been able to reproduce this bug very easily. do you mind letting me know which browser you're using? any addition steps or UI changes before you notice it would be helpful to know as well.

**Comment by jkamins7** [comment]
was using edge on windows.  didn't make any ui changes or other steps, but i can revisit if you're still unable to reproduce

**Comment by veev** [comment]
additional testing by @jkamins7 confirms that this bug happens if a user hovers on chart, then scrolls down to hover on counties in map, then back up to chart. the second time they try to hover on chart after map hover, tooltips do not appear.

**Comment by veev** [comment]
Closed #90
