### ISSUE TITLE
r0 selection showing fewer sims if there aren't enough as default number to show

### ISSUE THREAD

**Issue by veev** [HopkinsIDD/covid-dashboard-app#74]
this is strange behavior with the numDisplaySims is 30, and you select the r0filter to be 2 - 2.1. In this range, there are fewer than 30 possible to display, and for some reason the random sample selects 7. 
![image](https://user-images.githubusercontent.com/626371/85212930-c8aa7e80-b325-11ea-9f7a-b14bb3c42860.png)
![image (1)](https://user-images.githubusercontent.com/626371/85212932-cba56f00-b325-11ea-8aed-1df2500d8d31.png)

When you select 2.9-3, it shows the default 30 sims (likely because there are enough to show).
![image (2)](https://user-images.githubusercontent.com/626371/85212940-e11a9900-b325-11ea-8367-6dab38772da7.png)

**Comment by lxu213** [comment]
This bug should be resolved by e63c4a30341fc395091086c5711d41df47422ebc. Let me know if you still have issues!

**Comment by lxu213** [comment]
FYI, series will always return 'numDisplaySims', unless there aren't enough sins, which is the case for Inference scenario from 2-2.1, then it'll just return that set.

**Comment by veev** [comment]
Confirming this works! I also added [code](https://github.com/HopkinsIDD/covid-dashboard-app/commit/025783ceb41e47ad01c603701b791f47d41d788e#diff-eae5316532cb38411590ad1f4afad155) to Graph that removes simPaths if there are fewer than 'numDisplaySims'
